name: Example Workflow

on: [push]

permissions:
  contents: write
  checks: write

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Build with Maven
      run: mvn -B package

    - name: Copy test results
      if: always()
      run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JAVA Junit Tests            # Name of the check run which will be created
        path: 'test-results/**/*.xml'   # Path to test results
        reporter: java-junit        # Format of test results
